resources:
  repositories:
    - repository: templates
      type: github
      name: DagonMetric/ng-workspace-configs
      endpoint: github-dagonmetric-connection

trigger:
  branches:
    include:
    - master
    - releases/*
  tags:
    include:
    - v*
  paths:
    include:
    - modules/*
    - samples/*
    - angular-build.json
    - angular.json
    - package.json
    - tsconfig.json
    - tslint.json
    - 'README.md'
    - 'azure-pipelines.yml'

stages:
  - template: azure-pipelines/multi-platform-build-stage.yml@templates
    parameters:
      publishBuildArtifacts:
      - publishBuildArtifact:
        artifactName: 'packages'
        targetPath: 'dist/packages'
      publishTestArtifacts:
        - publishTestArtifact:
          testRunTitle: 'ng-translit'
          searchFolder: 'dist/junit/ng-translit'
      publishCodeCoverageArtifacts:
        - publishCodeCoverageArtifact:
          summaryFileLocation: 'dist/coverage/ng-translit/cobertura-coverage.xml'
          reportDirectory: 'dist/coverage/ng-translit'
