resources:
  repositories:
    - repository: templates
      type: github
      name: DagonMetric/ng-workspace-configs

trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - modules/*
    - samples/*
    - angular-build.json
    - angular.json
    - package.json
    - tsconfig.json
    - tslint.json
    - 'README.md'
    - 'azure-pipelines.yml'
  tags:
    include:
    - v*

jobs:
  - template: azure-pipelines/jobs.yml@templates
